# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='erp_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rq', models.CharField(max_length=150)),
                ('gys', models.CharField(max_length=150)),
                ('djbh', models.CharField(max_length=150)),
                ('wlmc', models.CharField(max_length=150)),
                ('ggxh', models.CharField(max_length=150)),
                ('sl', models.FloatField(max_length=50)),
                ('jhrq', models.CharField(max_length=150)),
                ('bb', models.CharField(max_length=150)),
                ('ywy', models.CharField(max_length=150)),
                ('ghjg', models.CharField(max_length=150)),
                ('wlcdm', models.CharField(max_length=150)),
                ('hsdj', models.FloatField(max_length=50)),
                ('dj', models.FloatField(max_length=50)),
                ('jshj', models.FloatField(max_length=50)),
                ('bm', models.CharField(max_length=150)),
                ('cydw', models.CharField(max_length=150)),
                ('fjs', models.FloatField(max_length=50)),
                ('btfjs', models.FloatField(max_length=50)),
                ('slsl', models.FloatField(max_length=50)),
                ('tlsl', models.FloatField(max_length=50)),
                ('zxbgbh', models.CharField(max_length=150)),
                ('jhlb', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
