# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0002_auto_20161125_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='erp_data',
            name='gbbz',
            field=models.CharField(blank=True, max_length=22),
        ),
        migrations.AddField(
            model_name='erp_data',
            name='shbz',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='bb',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='bm',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='btfjs',
            field=models.FloatField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='cydw',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='dj',
            field=models.FloatField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='djbh',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='fjs',
            field=models.FloatField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='ggxh',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='ghjg',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='gys',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='hsdj',
            field=models.FloatField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='jhlb',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='jhrq',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='jshj',
            field=models.FloatField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='rq',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='sl',
            field=models.FloatField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='slsl',
            field=models.FloatField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='tlsl',
            field=models.FloatField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='wlcdm',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='wlmc',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='ywy',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='zxbgbh',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
