# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0003_auto_20161125_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erp_data',
            name='gbbz',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
