# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0004_auto_20161125_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='erp_data',
            name='dw',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
