# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0005_erp_data_dw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erp_data',
            name='dw',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
