# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0007_remove_erp_data_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erp_data',
            name='btfjs',
            field=models.FloatField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='dj',
            field=models.FloatField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='fjs',
            field=models.FloatField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='hsdj',
            field=models.FloatField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='jshj',
            field=models.FloatField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='sl',
            field=models.FloatField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='slsl',
            field=models.FloatField(blank=True, default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='erp_data',
            name='tlsl',
            field=models.FloatField(blank=True, default=0, max_length=50),
        ),
    ]
