# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0014_auto_20161201_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
