# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0016_worklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='commreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=150, null=True)),
                ('product', models.CharField(max_length=150, null=True)),
                ('rq', models.CharField(max_length=150, null=True)),
                ('site', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
