# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gim', '0017_commreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='commreport',
            name='ping',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
